services:
  database_postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: obscuradb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://username:password@database_postgres:5432/obscuradb?sslmode=disable
    depends_on:
      - database_postgres

  s3_garage:
    image: dxflrs/garage:v1
    container_name: garage
    restart: always
    ports:
      - "3900:3900" # S3 API
      - "3902:3902" # Web Access
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./garage_data:/var/lib/garage
    environment:
      - RUST_LOG=info
